library(Rcpp)
library(Matrix)
sourceCpp("matrix_norm.cpp")
#set.seed(7)
#n=1
#A=matrix(rnorm(n**2), n)
#A=matrix(1:n**2*10, n)
#cppFunction('SEXP s1() {SEXP s=wrap("1"); return s;}')
#debug(Matrix::norm)
#gctorture(FALSE)
#s2()
#nmat(A)
gctorture(TRUE)
nmat(as.matrix(pi))
